### ISSUE TITLE
Test plan

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#45]
This year in order to make subsystem tests more efficient we had a discussion on how to check each subsystem. To work with this knowledge during testing this list needs to be organized and made into a checklist for each subsystem. The checklist should be in chronological order.

**Comment by vichik123** [comment]
[Shooter testing plans.docx](https://github.com/Galaxia5987/robot-2022/files/7935778/Shooter.testing.plans.docx)

**Comment by katzuv** [comment]
_Better to use Mardkown than uploading files._

## Stage 1
This stage involves playing with the state space constants until an optimal set of constants is achieved. The variables to consider are:
- [ ] Accuracy of the shooter. _Critical importance_
- [ ] Smoothness of the velocity by time function. _High importance_
- [ ] Speed in which the shooter gets to the required setpoint. This constraint does not need to be perfect, but it can’t be ridiculously slow. _Medium importance_

## Stage 2
Run the BITs one by one:
- [ ] `TestPistonPressure` – this test is designed to test the pressure of the piston by moving the ball manual to the edge of the hood. If the solenoid gives way, it’s time to cry for the mechanical team to fix it (break out the fake tears).
- [ ] `ShootAtMaximumVelocity` – this test is designed to test the maximal distance that the shooter can reach. Run this test on both angles of the shooter. Measure the distance that the ball traversed (approximately). In addition, make sure to check the error in the angle of the shooter (solenoid pressure).

## Stage 3
Shooting the ball! Shooting the ball! Shooting the ball! As made obvious by the previous statements, this stage involves shooting the ball to check the velocity of the shooter required to score the ball for each distance. Put the results into an Excel file and interpolate using the MATLAB spline function code here.

## Stage 4
Test the accuracy of the spline interpolation (more shooting). If the interpolation is not functioning properly, switch to linear interpolation here.

## Stage 5
Enjoy! Your shooter is ready, and your competition is trembling. Good luck!

**Comment by barel13** [comment]
Closed in favor of creating issue for each subsystem
