### ISSUE TITLE
Test Shooter Subsystem

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#73]
Add a checklist for checking the shooter here.

**Comment by vichik123** [comment]
## Stage 1
This stage involves playing with the state space constants until an optimal set of constants is achieved. The variables to consider are:
- [x] Accuracy of the shooter. _Critical importance_
- [x] Smoothness of the velocity by time function. _High importance_
- [x] Speed in which the shooter gets to the required setpoint. This constraint does not need to be perfect, but it can’t be ridiculously slow. _Medium importance_

## Stage 2
Run the BITs one by one:
- [ ] `ManualFlywheelControl` – this test is designed to test the pressure of the piston by moving the ball manual to the edge of the hood. If the solenoid gives way, it’s time to cry for the mechanical team to fix it (break out the fake tears).
- [ ] Using `Shoot` at maximal velocity – this test is designed to test the maximal distance that the shooter can reach. Run this test on both angles of the shooter. Measure the distance that the ball traversed (approximately). In addition, make sure to check the error in the angle of the shooter (solenoid pressure).

## Stage 3
Shooting the ball! Shooting the ball! Shooting the ball! As made obvious by the previous statements, this stage involves shooting the ball to check the velocity of the shooter required to score the ball for each distance. Put the results into an Excel file and interpolate using the MATLAB spline function code here.

## Stage 4
Test the accuracy of the spline interpolation (more shooting). If the interpolation is not functioning properly, switch to linear interpolation here.

## Stage 5
Enjoy! Your shooter is ready, and your competition is trembling. Good luck!
